INSERT INTO producto(IDProducto, Nombre, Precio, Stock, StockMinimo) VALUES(1, 'Arroz', 1200.00, 10, 15);
INSERT INTO producto(idProducto, nombre, precio, stock, stockminimo) VALUES(2, 'Natilla de la abuela', 2000.0, 0, 5);
INSERT INTO producto(idproducto, nombre, precio, stock, stockminimo) VALUES(3,'Cerveza importada', 5400.0, 90, 60);
INSERT INTO producto(idproducto, nombre, precio, stock, stockminimo) VALUES(4,'Cerveza nacional', 3100.0, 120,60);
INSERT INTO producto(idproducto, nombre, precio, stock, stockminimo) VALUES(5,'Botella de vino', 30100.0, 10, 5);
INSERT INTO producto(idproducto, nombre, precio, stock, stockminimo) VALUES(6,'Agua', 2700.0, 10, 5);
INSERT INTO producto(idproducto, nombre, precio, stock, stockminimo) VALUES(7,'Lechuga', 2500.0, 5, 3);
INSERT INTO producto(idproducto, nombre, precio, stock, stockminimo) VALUES(8,'Cebollas', 2900.0, 5, 3);
INSERT INTO producto(idproducto, nombre, precio, stock, stockminimo) VALUES(9,'Patatas', 2500, 15, 10);
INSERT INTO producto(idproducto, nombre, precio, stock, stockminimo) VALUES(10,'Tomates', 3600.0, 15, 10);